language: go

go:
 - tip

before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - go get github.com/onsi/ginkgo/ginkgo
 - go get github.com/modocache/gover

script:
 - $HOME/go/bin/ginkgo -r  -cover -coverpkg=./GoBDD/services/... -trace -race
 - $HOME/go/bin/gover
 - $HOME/go/bin/goveralls -coverprofile=gover.coverprofile -repotoken "gmCgzuy1x8PxJU7QTpKh" 
